### ISSUE TITLE
Pre-commit and requirements-dev.txt mismatch

### ISSUE THREAD

**Issue by wildintellect** [stactools-packages/template#78]
**Is your feature request related to a problem? Please describe.**
When doing a PR `cibuild` installs based on https://github.com/stactools-packages/template/blob/main/requirements-dev.txt however `pre-commit` pins versions in https://github.com/stactools-packages/template/blob/main/.pre-commit-config.yaml this can lead to situation where the version used in pre-commit is not the same as CI tests, which can have different results.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. I would like to
use stac \<package\> to do [...]

requirements-dev.txt should probably pin versions, and/or be used as part of pre-commit in some way. Or the versions should be synced between the two.

**Describe alternatives you've considered**

We could do nothing and just keep patching piecemeal as cibuilds break.

**Additional context**

Example, previously working code now fails simply by passage of time. https://github.com/stactools-packages/palsar2-scansar/actions/runs/5381124480/jobs/9764779545?pr=7 where mypy during the PR is much newer than pre-commit so new errors weren't caught (need to verify there are actually errors and not a mypy bug)

Also local Docker environments for testing will invoke different versions is `scripts/lint` is run manually before `pre-commit`

**Comment by gadomski** [comment]
We've run into this before ... I'm a little reluctant to use `system` for pre-commit (it's what we do in pystac: https://github.com/stac-utils/pystac/blob/3bf0676f5265f36ca258e7dc4e1b13bc4c3d459b/.pre-commit-config.yaml#L15-L20) because it breaks the "normal way" of doing pre-commit and I've had it produce some strange, unexpected errors. I don't have an example on hand so you'll have to trust me on that one :-).

One approach we've taken is to add a `pre-commit autoupdate` step to every release, so at the very least you're refreshing your pre-commit pins at some sort of interval. I think in general a `pre-commit autoupdate`, coupled with regular dependabot checks on your development requirements, _should_ keep things relatively in-sync.

I'm reluctant to build a solution that uses `requirements-dev.txt` because we've been moving away from that pattern in favor of putting everything in `pyproject.toml`, e.g. https://github.com/stac-utils/pystac/blob/3bf0676f5265f36ca258e7dc4e1b13bc4c3d459b/pyproject.toml#L52-L72.
